anomusix/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("dev/", admin.site.urls),
    path('music/', include(('music.urls', 'anomusix'), namespace='music'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # urlpatterns += staticfiles_urlpatterns()
    #
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

music/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),

    # path('song/<int:song_id>/', show_song, name='song'),

    path('category/<int:category_id>/', show_category, name='category'),
    path('detailed/<int:pk>', detailed, name='detailed'),

    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),

]

# делаю проект на основе сайта SEFON.SU

music/models.py
from django.db import models
from django.urls import reverse


class Music(models.Model):
    audio = models.FileField('Песня', upload_to='uploads/%Y/%m/%d/')
    cover = models.ImageField('Обложка', upload_to='uploads/%Y/%m/%d', default='default_note.jpg', null=True)
    author = models.ForeignKey('Author', on_delete=models.PROTECT,
                               verbose_name='Исполнитель', null=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT,
                                 verbose_name='Категория', null=True)
    name = models.CharField('Название', max_length=100)

    class Meta:
        verbose_name = 'Песня'
        verbose_name_plural = 'Песни'
        ordering = ['-id']

    def __str__(self):
        return f'{self.name} — {self.author.name}'

    def get_absolute_url(self):
        return reverse('music:song', kwargs={'song_id': self.pk})


class Author(models.Model):
    name = models.CharField('Имя исполнителя', max_length=50)

    class Meta:
        verbose_name = 'Исполнитель'
        verbose_name_plural = 'Исполнители'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('Название категории', max_length=100)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('music:category', kwargs={'category_id': self.pk})


class BestSong(Music):
    pass

users/models.py
from django.db import models

# Create your models here.

music/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
        }


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'password': forms.PasswordInput(attrs={'class': 'form-input'})
        }

music/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .forms import *
from .models import *

class HomePage(ListView):
    paginate_by = 4
    model = Music
    template_name = 'music/main.html'
    context_object_name = 'songs'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['category_selected'] = 0
        context['best'] = BestSong.objects.all()
        return context


def show_song(request, song_id):
    return HttpResponse(f"Отображение статьи с id = {song_id}")


class SongCategory(ListView):
    paginate_by = 4
    model = Music
    template_name = 'music/main.html'
    context_object_name = 'songs'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['songs'] = Music.objects.filter

def show_category(request, category_id):
    songs = Music.objects.filter(category_id=category_id)
    categories = Category.objects.all()
    best = BestSong.objects.all()

    context = {
        'songs': songs,
        'categories': categories,
        'best': best,
    }

    return render(request, 'music/main.html', context=context)


def detailed(request, pk):
    song = Music.objects.get(pk=pk)
    categories = Category.objects.all()
    best = BestSong.objects.all()

    context = {
            'song': song,
            'categories': categories,
            'best': best,
    }

    return render(request, 'music/detailed.html', context=context)


# def homepage(request):
#     singers = Author.objects.all()
#     songs = Music.objects.all()
#
#     context = {
#         'songs': songs,
#         'singers': singers,
#     }
#
#     return render(request, 'music/main.html', context=context)
#


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'music/register.html'
    success_url = reverse_lazy('music:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('music:homepage')


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'music/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))

    def get_success_url(self):
        return reverse_lazy('music:homepage')


def logout_user(request):
    logout(request)
    return redirect('music:homepage')

users/views.py
from django.shortcuts import render

# Create your views here.

music/templates/music/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

{#    <link rel="stylesheet"#}
{#          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"#}
{#          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="#}
{#          crossorigin="anonymous" referrerpolicy="no-referrer"/>#}

    {#    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">#}

    <link rel="stylesheet" href="{% static 'css/detailed.css' %}">
    <link rel="stylesheet" href="{% static 'css/users.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="wrapper">

    <header class="header">

        <div class="nav">

            <div class="nav__item">
                <a href="{% url 'music:homepage' %}" class="brand">
                    <img src="{% static 'img/anomusix.png' %}" width="200"
                         alt="anomusix">
                </a>
            </div>

{#            {% if user.is_authenticated %}#}

            <div class="search_n_login">

                <div class="nav__item"><input class="search" type="search"
                                              placeholder="Найти песню...">
                </div>

                {#-----------------------------------------------------------------------#}

                <div class="nav__item">

                {% if not user.is_authenticated %}

                    <a id="open-modal-btn" class="login">
                        Login
                    </a>

                {% else %}
                    <div class="user-logout" style="display: flex; align-items: center; gap: 0 0px; border: 2px solid white; border-radius: 5px; padding: 0 0 0 10px; background: #5d5e5e;">

                        <h1 class="username" style="color: white; border-right: 2px solid white; padding-right: 11px;">{{ user.username }}</h1>

                        <a class="logout-btn" href="{% url 'music:logout' %}">Выйти</a>

                    </div>

                {% endif %}

                </div>

                <div class="modal" id="my-modal">
                    <div class="modal__box">
                        <button id="close-my-modal-btn" class="modal__close-btn"><ion-icon name="close-outline"></ion-icon></button>

                        <a href="{% url 'music:register' %}" class="register-btn">Регистрация</a>
                        <a href="{% url 'music:login' %}" class="login-btn">Вход</a>

                    </div>
                </div>

                {#-----------------------------------------------------------------------#}
            </div>

{#            {% endif %}#}


        </div>

    </header>

    <main class="main">

        <aside class="left__side">
            <h1 class="playlist">
                <img src="{% static 'img/musical-note.svg' %}" class="playlist__icon">
                Плейлисты
            </h1>
            <ul class="categories">

                {% for c in categories %}

                    {% if c.pk == category_selected %}

                        <li class="category__item">
                            <ion-icon name="disc-outline"
                                      style="color: yellow"></ion-icon>
                            {{ c.name }}
                        </li>

                    {% else %}

                        <a href="{{ c.get_absolute_url }}">
                            <li class="category__item">
                                <img src="{% static 'img/disc.svg' %}" width="18px">
                                {{ c.name }}
                            </li>
                        </a>

                    {% endif %}

                {% endfor %}

            </ul>
        </aside>

        <div class="center__side">
            {% block main %}
            {% endblock %}
            {% if page_obj.has_other_pages %}

                <ul class="list__pages">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">
                            <li class="page__num">&blacktriangleleft;</li>
                        </a>
                    {% endif %}


                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <li class="page__num-selected">{{ p }}</li>
                        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}

                            <a href="?page={{ p }}">
                                <li class="page__num">{{ p }}</li>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">
                            <li class="page__num">&blacktriangleright;</li>
                        </a>
                    {% endif %}
                </ul>

            {% endif %}
            {#        sefon.ru#}
        </div>

        <aside class="right__side">

            <h1 class="hit__songs">
                <img src="{% static 'img/flame.svg' %}" width="25px">
                Лучшие песни
            </h1>

            <hr>

            {% for b in best %}

                <a href="{% url 'music:detailed' pk=b.pk %}" class="best__song">

                    <p class="best__author-n-name">

                        <img src="{% static 'img/radio-button-on.svg' %}" width="15px">

                        {{ b.author }} - {{ b.name }}

                    </p>

                </a>

            {% endfor %}

        </aside>

    </main>

    <footer class="footer">

        <p class="footer__text">Слушайте музыку бесплатно или скачайте в формате mp3.</p>
    </footer>

</div>


<script type="module"
        src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>

<script nomodule
        src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

<script src="{% static 'js/modal.js' %}"></script>

<script src="{% static 'js/player.js' %}"></script>

</body>
</html>

music/templates/music/detailed.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}Скачать {{ song.name }}{% endblock %}

{% block main %}

    <p class="song__author">{{ song.author }}</p>

    <p class="song__name">{{ song.name }}</p>

    <div class="song__attrs">

    <img src="{{ song.cover.url }}" width="300" height="200" alt="{{ song.name }}" class="song__cover">

    <div class="song__btns">

        <a href="{{ song.audio.url }}" class="listen__btn">

            <img src="{% static 'img/play.svg' %}" class="btn__icon-1">
            <button class="download__format-1">
                <p>Слушать</p>
            </button>

        </a><a href="{{ song.audio.url }}" download class="download__btn">

            <img src="{% static 'img/arrow-down-circle.svg' %}" class="btn__icon-2">
            <button class="download__format-2">
                <p>Скачать</p>
                <p>{{ song.name }}.mp3</p>
            </button>

        </a>

    </div>

    </div>


{% endblock %}

music/templates/music/login.html
{% extends 'music/base.html' %}

{% block title %}Авторизация{% endblock %}

{% block main %}

    <form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}

        <p class="form-align">
            <label class="form-label" style="padding: 0 10px;" for="{{ f.id_for_label }}">{{ f.label }}: </label>
            {{ f }}
        </p>

        <div class="form-error">{{ f.errors }}</div>

    {% endfor %}

    <button type="submit" class="login-conf">Войти</button>
    </form>

{% endblock %}

music/templates/music/main.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}Слушайте музыку бесплатно{% endblock %}

{% block main %}

    <h1 class="page__title">Музыка со всего мира</h1>

    <div class="audio__items">
        {% for s in songs %}

            {#            <div class="audio__item">#}
            {#                <audio controls {# loop >#}
            {#                    <source src="{{ s.audio.url }}">#}
            {#                    На вашем браузере не поддерживаются аудио файлы.#}
            {#                </audio>#}
            {#                <a href="{% url 'music:song' s.pk %}">#}
            {#                    <ion-icon name="arrow-down-circle-outline" class="download"></ion-icon>#}
            {#                </a>#}
            {#            </div>#}

            <div class="audio__item">

                <audio-player title="{{ s.author }} / {{ s.name }}"
                              src="{{ s.audio.url }}">
                </audio-player>

                <a href="{# {{ s.audio.url }} #}{% url 'music:detailed' pk=s.pk %}"
                        {# download #}>
                    <svg class="download" xmlns="http://www.w3.org/2000/svg" width="512"
                         height="512" fill="#fff" viewBox="0 0 512 512">
                        <path d="M256,464c114.87,0,208-93.13,208-208S370.87,48,256,48,48,141.13,48,256,141.13,464,256,464ZM164.64,251.35a16,16,0,0,1,22.63-.09L240,303.58V170a16,16,0,0,1,32,0V303.58l52.73-52.32A16,16,0,1,1,347.27,274l-80,79.39a16,16,0,0,1-22.54,0l-80-79.39A16,16,0,0,1,164.64,251.35Z"/>
                    </svg>
                </a>

            </div>

        {% endfor %}

        {#    <audio class="audio__item" src="{% static 'audio/grunt-2.mp3' %}" controls preload="none">Аудио</audio>#}
        {#    <audio class="audio__item" src="{% static 'audio/haha.mp3' %}" controls preload="none">Аудио</audio> #}

    </div>


{% endblock %}

music/templates/music/register.html
{% extends 'music/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block main %}

<form method="post">
    {% csrf_token %}

    {% for f in form %}

        <p class="form-align">
            <label class="form-label" style="padding: 0 10px;" for="{{ f.id_for_label }}">{{ f.label }}: </label>
            {{ f }}
        </p>

        <div class="form-error">{{ f.errors }}</div>

    {% endfor %}

    <button type="submit" class="register-conf">Зарегистрироваться</button>

</form>

{% endblock %}